describe('Tour All modules', () => {
  it('FarmLink', () => {
    cy.visit('http://localhost:3000')
   const email= cy.get(`input[name="email"]`)
   email.type("usama@gmail.com")
   const password=cy.get(`input[name="password"]`)
   password.type("12345678!Qq")
    const submit=cy.get(`#login`)
    submit.click()
    cy.wait(3000)
    cy.get(`#dashboard`).click()
    cy.wait(3000)
    cy.get(`#inventory`).click()
    cy.wait(3000)
    cy.get(`#sales`).click()
    cy.wait(3000)
    cy.get(`#order`).click()
    cy.wait(3000)
    cy.get(`#emp`).click()
    cy.wait(3000)
    cy.get(`#post`).click()
    cy.wait(3000)
    cy.get(`#bid`).click()
    cy.wait(3000)
    cy.get(`#chat`).click()
    cy.wait(3000)
    cy.get(`#forder`).click()
    cy.wait(3000)
    cy.get(`#doctor`).click()
    cy.wait(3000)
    cy.get(`#aichat`).click()
    cy.wait(3000)
    cy.get(`#expence`).click()
  })
})